// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gene_cdf_poisson_cpp
NumericMatrix gene_cdf_poisson_cpp(NumericMatrix expr, int row_start, int row_end);
RcppExport SEXP _scGSVA_gene_cdf_poisson_cpp(SEXP exprSEXP, SEXP row_startSEXP, SEXP row_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< int >::type row_start(row_startSEXP);
    Rcpp::traits::input_parameter< int >::type row_end(row_endSEXP);
    rcpp_result_gen = Rcpp::wrap(gene_cdf_poisson_cpp(expr, row_start, row_end));
    return rcpp_result_gen;
END_RCPP
}
// gene_cdf_gaussian_cpp
NumericMatrix gene_cdf_gaussian_cpp(NumericMatrix expr, int row_start, int row_end);
RcppExport SEXP _scGSVA_gene_cdf_gaussian_cpp(SEXP exprSEXP, SEXP row_startSEXP, SEXP row_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< int >::type row_start(row_startSEXP);
    Rcpp::traits::input_parameter< int >::type row_end(row_endSEXP);
    rcpp_result_gen = Rcpp::wrap(gene_cdf_gaussian_cpp(expr, row_start, row_end));
    return rcpp_result_gen;
END_RCPP
}
// ssgsea_cpp
NumericMatrix ssgsea_cpp(NumericMatrix expr, List gene_sets_list, double alpha);
RcppExport SEXP _scGSVA_ssgsea_cpp(SEXP exprSEXP, SEXP gene_sets_listSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets_list(gene_sets_listSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(ssgsea_cpp(expr, gene_sets_list, alpha));
    return rcpp_result_gen;
END_RCPP
}
// ssgsea_from_ranks_cpp
NumericMatrix ssgsea_from_ranks_cpp(NumericMatrix R_mat, NumericMatrix Ra_mat, List gene_sets_list);
RcppExport SEXP _scGSVA_ssgsea_from_ranks_cpp(SEXP R_matSEXP, SEXP Ra_matSEXP, SEXP gene_sets_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type R_mat(R_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ra_mat(Ra_matSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets_list(gene_sets_listSEXP);
    rcpp_result_gen = Rcpp::wrap(ssgsea_from_ranks_cpp(R_mat, Ra_mat, gene_sets_list));
    return rcpp_result_gen;
END_RCPP
}
// gsva_pipeline_cpp
NumericMatrix gsva_pipeline_cpp(NumericMatrix expr, List gene_sets_list, int kcdf, double tau, bool max_diff, bool abs_ranking);
RcppExport SEXP _scGSVA_gsva_pipeline_cpp(SEXP exprSEXP, SEXP gene_sets_listSEXP, SEXP kcdfSEXP, SEXP tauSEXP, SEXP max_diffSEXP, SEXP abs_rankingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets_list(gene_sets_listSEXP);
    Rcpp::traits::input_parameter< int >::type kcdf(kcdfSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type max_diff(max_diffSEXP);
    Rcpp::traits::input_parameter< bool >::type abs_ranking(abs_rankingSEXP);
    rcpp_result_gen = Rcpp::wrap(gsva_pipeline_cpp(expr, gene_sets_list, kcdf, tau, max_diff, abs_ranking));
    return rcpp_result_gen;
END_RCPP
}
// gsva_score_cpp
NumericMatrix gsva_score_cpp(IntegerMatrix rank_matrix, List gene_sets_list, double tau, bool max_diff, bool abs_ranking);
RcppExport SEXP _scGSVA_gsva_score_cpp(SEXP rank_matrixSEXP, SEXP gene_sets_listSEXP, SEXP tauSEXP, SEXP max_diffSEXP, SEXP abs_rankingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type rank_matrix(rank_matrixSEXP);
    Rcpp::traits::input_parameter< List >::type gene_sets_list(gene_sets_listSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type max_diff(max_diffSEXP);
    Rcpp::traits::input_parameter< bool >::type abs_ranking(abs_rankingSEXP);
    rcpp_result_gen = Rcpp::wrap(gsva_score_cpp(rank_matrix, gene_sets_list, tau, max_diff, abs_ranking));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scGSVA_gene_cdf_poisson_cpp", (DL_FUNC) &_scGSVA_gene_cdf_poisson_cpp, 3},
    {"_scGSVA_gene_cdf_gaussian_cpp", (DL_FUNC) &_scGSVA_gene_cdf_gaussian_cpp, 3},
    {"_scGSVA_ssgsea_cpp", (DL_FUNC) &_scGSVA_ssgsea_cpp, 3},
    {"_scGSVA_ssgsea_from_ranks_cpp", (DL_FUNC) &_scGSVA_ssgsea_from_ranks_cpp, 3},
    {"_scGSVA_gsva_pipeline_cpp", (DL_FUNC) &_scGSVA_gsva_pipeline_cpp, 6},
    {"_scGSVA_gsva_score_cpp", (DL_FUNC) &_scGSVA_gsva_score_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_scGSVA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
