# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gene_cdf_poisson_cpp <- function(expr, row_start = 0L, row_end = -1L) {
    .Call(`_scGSVA_gene_cdf_poisson_cpp`, expr, row_start, row_end)
}

gene_cdf_gaussian_cpp <- function(expr, row_start = 0L, row_end = -1L) {
    .Call(`_scGSVA_gene_cdf_gaussian_cpp`, expr, row_start, row_end)
}

ssgsea_cpp <- function(expr, gene_sets_list, alpha) {
    .Call(`_scGSVA_ssgsea_cpp`, expr, gene_sets_list, alpha)
}

ssgsea_from_ranks_cpp <- function(R_mat, Ra_mat, gene_sets_list) {
    .Call(`_scGSVA_ssgsea_from_ranks_cpp`, R_mat, Ra_mat, gene_sets_list)
}

gsva_pipeline_cpp <- function(expr, gene_sets_list, kcdf, tau, max_diff, abs_ranking) {
    .Call(`_scGSVA_gsva_pipeline_cpp`, expr, gene_sets_list, kcdf, tau, max_diff, abs_ranking)
}

gsva_score_cpp <- function(rank_matrix, gene_sets_list, tau, max_diff, abs_ranking) {
    .Call(`_scGSVA_gsva_score_cpp`, rank_matrix, gene_sets_list, tau, max_diff, abs_ranking)
}

